const pages=["home","presence","mindsets","body-language","strength-style","practice","summary"];
const storageKey="hftb-interview-skills-v1";
const emptyWorkbook=()=>({version:2,mindsets:{},body:{},styles:{},scenarios:{},choices:{},lastPage:"home",updatedAt:null});
let workbook=emptyWorkbook(),restoredSession=false,storageWorks=true;

const mindsets=[
  {id:"okay",title:"No matter what, I will be okay",meaning:"The interview matters, but one outcome does not determine your worth or future.",use:"Reduces threat and helps your personality remain available."},
  {id:"invite",title:"I do not need to convince anyone",meaning:"Present your background clearly and invite the employer to explore mutual fit.",use:"Replaces approval-seeking with professional confidence."},
  {id:"humanize",title:"Go first in humanizing the interaction",meaning:"Offer the first warm greeting, natural smile, or appropriate moment of connection.",use:"Helps the conversation feel human instead of rigid."},
  {id:"purpose",title:"Proactively share my purpose",meaning:"Explain what motivates your work and what problem you want to help solve.",use:"Connects your experience to a meaningful direction."},
  {id:"honesty",title:"Use impeccable honesty and integrity",meaning:"Discuss strengths, gaps, and mistakes truthfully without exaggeration or defensiveness.",use:"Supports trust and steadier answers."},
  {id:"character",title:"Character matters more than reputation",meaning:"Answer from your values instead of performing solely for approval or appearances.",use:"Keeps your message consistent and believable."}
];
const mechanics=[
  {id:"movement",icon:"↘",title:"Slow the movement",text:"Anxiety can create darting eyes, jerky gestures, and rushed motion. Deliberately slower movement appears more grounded and helps your body settle."},
  {id:"space",icon:"↔",title:"Use comfortable space",text:"Unpin your elbows and use natural gestures within your space. Open palms can communicate engagement; exaggerated gestures are unnecessary."},
  {id:"alignment",icon:"◎",title:"Turn the whole body",text:"When addressing someone, align your eyes, head, chest, and torso toward them instead of looking sideways while the body stays frozen."},
  {id:"silence",icon:"Ⅱ",title:"Replace fillers with pauses",text:"A short pause is stronger than repeated “um,” “ah,” or other crutch words. It gives you time and helps the interviewer follow your answer."},
  {id:"finish",icon:"●",title:"Finish the sentence",text:"Complete the thought clearly, lower the voice naturally at the end, and then pause. Do not let every answer trail away."},
  {id:"prime",icon:"⚡",title:"Prime the physical state",text:"Before entering, use movement, breathing, posture, or a vocal warm-up. A useful cue is: “I deserve to be here, and I am ready to have a conversation.”"}
];
const styleInfo={
  conviction:{name:"High Conviction",description:"You create confidence through certainty, decisive language, and clear belief in a direction.",strengths:["Confident delivery","Firm sentence endings","Clear goals"],watch:"Certainty can sound rigid if you do not show curiosity or openness to coaching.",practice:"Pair conviction with one thoughtful question and acknowledge where you are still learning."},
  authentic:{name:"Authentic",description:"You create trust through honesty, directness, and a willingness to discuss the real story.",strengths:["Credibility","Natural connection","Honest discussion of gaps"],watch:"Being genuine does not mean sharing every detail or speaking without professional boundaries.",practice:"Keep the truth relevant: situation, lesson, change, and current readiness."},
  funny:{name:"Warm & Lighthearted",description:"You reduce tension through warmth, appropriate humor, and an enjoyable conversational style.",strengths:["Rapport","Memorable interaction","Calm recovery from awkward moments"],watch:"Too much humor can distract from qualifications or feel poorly timed.",practice:"Use light humor sparingly, then return clearly to the question and evidence."},
  empathetic:{name:"Empathetic",description:"You create connection by listening carefully and showing that you understand the interviewer’s needs.",strengths:["Active listening","Strong questions","Relationship awareness"],watch:"You may focus so much on the other person that your own value and results become unclear.",practice:"After listening, connect their stated need to one specific example of what you can contribute."},
  energetic:{name:"Energetic",description:"You create momentum through enthusiasm, warmth, vocal variety, and visible interest.",strengths:["Positive first impression","Enthusiasm","Engaging delivery"],watch:"High energy can become rushed speech, interruption, or oversized gestures.",practice:"Keep the warmth while slowing the pace and allowing the interviewer to finish."}
};
const styleQuestions=[
  ["c1","conviction","I speak about my abilities and goals with clear belief."],["a1","authentic","I am comfortable giving an honest answer instead of a polished but untrue one."],["f1","funny","I naturally use appropriate warmth or light humor to reduce tension."],["e1","empathetic","I listen closely for what the interviewer or team truly needs."],["n1","energetic","My enthusiasm is visible in my voice and expression."],
  ["c2","conviction","I finish answers firmly instead of trailing off."],["a2","authentic","I can discuss a mistake or gap without becoming defensive."],["f2","funny","I can recover from an awkward moment without becoming rigid."],["e2","empathetic","I ask sincere questions that help me understand workplace priorities."],["n2","energetic","I bring positive energy that is slightly higher than the room."],
  ["c3","conviction","When challenged, I can stay steady and explain my reasoning."],["a3","authentic","My answers sound like me rather than memorized corporate language."],["f3","funny","People often find conversations with me comfortable and enjoyable."],["e3","empathetic","I make people feel heard before I respond."],["n3","energetic","I use vocal variety and open body language to stay engaging."]
];
const questionCoaching={
  c1:"Write two sentences connecting your experience to the job, then say them without “maybe” or “I guess.”",c2:"Record one 60-second answer. End with the result, stop speaking, and hold a two-second pause.",c3:"Practice: acknowledge the concern, give one fact, explain your reasoning, and stay open to feedback.",
  a1:"Prepare one truthful answer about a limitation, related experience, and a realistic learning plan.",a2:"Use four parts for a gap or mistake: context, responsibility, lesson, and what is different now.",a3:"Replace one memorized answer with three bullet points and speak naturally from them.",
  f1:"Prepare one warm opening sentence. Do not force a joke.",f2:"Practice recovering with: “Let me say that more clearly,” followed by a direct answer.",f3:"Ask someone whether you appear comfortable and approachable during a practice interview.",
  e1:"Listen for one employer need and connect your next example directly to it.",e2:"Prepare two questions about priorities, team needs, or success after 90 days.",e3:"Before responding, briefly reflect the interviewer’s point.",
  n1:"Practice a clear greeting, natural smile, and slightly more energy than an ordinary conversation.",n2:"Add vocal variety while keeping your pace controlled.",n3:"Record one answer and check for visible interest, open posture, and comfortable gestures."
};
const scenarios=[
  {id:"s1",question:"The interviewer asks about a gap in employment.",choices:["Avoid the question and immediately change the subject.","Give a brief honest explanation, state what you did during the period, and explain why you are ready now.","Invent a role so the timeline looks stronger.","Apologize repeatedly for the gap."],correct:1,feedback:[
    {heading:"Avoiding the gap creates more concern.",impact:"Changing the subject may make the interviewer think you are hiding something or cannot discuss difficult topics directly.",coaching:"Answer briefly, protect private details, and move the conversation toward what you did and why you are ready now.",sample:"I took time away from work to address a personal matter that is now resolved. During that period I kept my skills current, and I am ready to return to reliable, full-time work."},
    {heading:"Strong choice: honest, brief, and forward-looking.",impact:"This shows integrity, self-awareness, and current readiness without turning the interview into a long personal explanation.",coaching:"Keep the explanation under about 30 seconds and finish by connecting your readiness to this position.",sample:"I stepped away from work for a family responsibility that has been resolved. I used the time productively, and I am now prepared to bring my experience and reliability to this role."},
    {heading:"Inventing experience can end the hiring process.",impact:"A false role can be uncovered during reference or background checks and raises a serious integrity concern.",coaching:"Never create employment that did not happen. Use truthful volunteer work, training, caregiving, recovery, or skill-building when relevant.",sample:"I was not formally employed during that period. I was handling personal responsibilities and working on my readiness to return. I can explain the relevant skills I maintained and why I am ready now."},
    {heading:"Repeated apologies weaken an otherwise manageable answer.",impact:"Over-apologizing can make a normal employment gap sound like a continuing problem and can signal low confidence.",coaching:"Acknowledge the gap once, state the useful facts, and finish with present readiness—not shame.",sample:"There is a gap in my employment history because I needed to address a personal matter. That situation is stable now, and I am focused on returning to work and contributing consistently."}
  ]},
  {id:"s2",question:"You need several seconds to organize a difficult answer.",choices:["Begin speaking immediately and use filler words until the answer appears.","Say, “That is a good question. Let me think for a moment,” pause, and then answer.","Tell the interviewer the question is unfair.","Give the shortest possible answer and look away."],correct:1,feedback:[
    {heading:"Filling the silence makes the answer harder to follow.",impact:"A stream of “um,” “like,” and unfinished thoughts may sound unprepared even when you know the subject.",coaching:"Use one professional sentence to claim thinking time, pause, and organize the answer into situation, action, and result.",sample:"That is a good question. Let me think of the strongest example for a moment. [Pause.] In my last position, the situation was…"},
    {heading:"Strong choice: a deliberate pause shows control.",impact:"This communicates thoughtfulness and confidence. The interviewer can see that you are selecting a relevant example instead of panicking.",coaching:"Keep the pause comfortable—usually three to five seconds—then answer directly with a specific example.",sample:"Let me take a moment to organize that. [Pause.] A good example would be when I had to resolve…"},
    {heading:"Calling the question unfair sounds defensive.",impact:"The interviewer may conclude that you resist pressure, feedback, or reasonable follow-up questions.",coaching:"If the question is unclear, request clarification without accusing the interviewer.",sample:"I want to make sure I answer what you are asking. Would you like an example from my most recent job or from any point in my work history?"},
    {heading:"A rushed answer and looking away can appear evasive.",impact:"It may suggest discomfort, lack of interest, or that you have not fully considered the question.",coaching:"Stay visually engaged, pause, and give one complete point instead of escaping with the shortest answer possible.",sample:"I would like a moment to think about that. [Pause.] The main lesson I learned was…, and here is how I applied it afterward."}
  ]},
  {id:"s3",question:"You do not have every qualification listed in the posting.",choices:["Claim that you have experience you do not have.","Focus only on the missing qualification.","Acknowledge the gap, connect related experience, and explain a realistic learning plan.","Tell the employer the requirement is unnecessary."],correct:2,feedback:[
    {heading:"Claiming experience you do not have is a serious risk.",impact:"The employer may test the skill, check references, or discover the claim after hiring. That turns a trainable gap into an integrity problem.",coaching:"State the gap honestly, then bridge to related experience and evidence that you can learn the missing skill.",sample:"I have not used that exact system yet. I have used similar software to complete comparable tasks, and I am prepared to complete training and practice before my start date."},
    {heading:"Focusing only on the gap undersells you.",impact:"The interviewer hears what you cannot do but receives no reason to believe you can succeed.",coaching:"Mention the missing qualification once, then spend most of the answer on transferable skills, results, and your learning plan.",sample:"I do not yet have direct experience with that tool, but I have three years of related technical work, including troubleshooting and documentation. I would use the same learning process to become productive quickly."},
    {heading:"Strong choice: honest, relevant, and coachable.",impact:"This protects your credibility while showing that the missing qualification may be manageable.",coaching:"Make the answer convincing by naming one related skill, one past learning success, and one concrete step you will take.",sample:"I have not worked with that exact platform. I have used two comparable systems and learned the second one during my first month on the job. I would complete the available training and practice in a test environment so I can contribute quickly."},
    {heading:"Dismissing the requirement challenges the employer’s judgment.",impact:"It can sound arrogant and suggests that you may resist standards, instructions, or coaching.",coaching:"Respect the requirement even if you do not fully understand it. Ask how the skill is used and explain how you would close the gap.",sample:"I noticed that requirement and would like to understand how often the team uses it. I have related experience, and I am willing to complete the training needed to meet your standard."}
  ]},
  {id:"s4",question:"The interviewer asks, “Why do you want this job?”",choices:["Give only a list of duties from the posting.","Say that you will take any available job.","Connect the employer’s needs with your experience, interests, and the contribution you want to make.","Describe only what you want the employer to give you."],correct:2,feedback:[
    {heading:"Repeating the posting does not explain your motivation.",impact:"It proves you read the duties, but it does not show why this organization, team, or work matters to you.",coaching:"Select one employer need, connect it to your experience, and explain the contribution you want to make.",sample:"I am interested because this role combines customer service with problem-solving. Those are strengths I used successfully in my last position, and I would like to apply them on a team that values reliable service."},
    {heading:"“I will take any job” signals desperation, not fit.",impact:"The employer may doubt that you understand the role or will remain after a different opportunity appears.",coaching:"You can be honest about needing work while still naming real reasons this particular job fits your skills and goals.",sample:"I am actively looking for work, and this position stands out because it uses my experience in scheduling, customer communication, and solving day-to-day problems."},
    {heading:"Strong choice: it connects motivation with employer value.",impact:"The answer shows that you understand the job, have relevant evidence, and are interested in contributing—not only receiving a paycheck.",coaching:"Make it specific by naming the employer, one important need, and one example of relevant success.",sample:"I want this position because your team needs someone who can keep customers informed and solve problems calmly. In my last role, I handled high-volume requests while maintaining accurate records, and I would bring that same reliability here."},
    {heading:"Discussing only what you will receive sounds one-sided.",impact:"Pay, benefits, and advancement matter, but leading only with them can make the employer question your interest in the work itself.",coaching:"Balance what attracts you with what you can contribute to the employer.",sample:"The stability and growth opportunity are attractive, and I am also interested because my experience in inventory accuracy and team coordination matches what this department needs."}
  ]},
  {id:"s5",question:"The interviewer seems formal and reserved.",choices:["Force jokes into the conversation.","Match the professional tone, remain warm, and let rapport build naturally.","Assume they dislike you and become withdrawn.","Increase your volume and energy until they respond."],correct:1,feedback:[
    {heading:"Forced humor ignores the interviewer’s communication style.",impact:"It can feel distracting, uncomfortable, or like you are trying too hard to win approval.",coaching:"Remain friendly without performing. Let humor appear naturally only if the interviewer’s response supports it.",sample:"Good morning. Thank you for meeting with me. I have been looking forward to learning more about the position and your team."},
    {heading:"Strong choice: warm professionalism shows adaptability.",impact:"You respect the interviewer’s pace while remaining confident, interested, and approachable.",coaching:"Use a calm greeting, attentive posture, and thoughtful answers. Allow rapport to develop instead of forcing it.",sample:"Thank you for the opportunity to speak with you. I reviewed the position carefully, and I am ready to discuss how my experience could support the team."},
    {heading:"A reserved style does not automatically mean rejection.",impact:"Withdrawing may create the very disconnection you fear and can make your answers sound uncertain or uninterested.",coaching:"Do not mind-read. Stay engaged, answer fully, and judge the interview from the actual questions and follow-up—not facial expression alone.",sample:"I appreciate the question. A relevant example from my last position is…, and the result was…"},
    {heading:"More volume is not the same as more connection.",impact:"Overpowering a reserved interviewer can look socially unaware and may make the conversation less comfortable.",coaching:"Keep positive energy, but slow your pace and match the room’s professional intensity.",sample:"I am very interested in the position. I will walk you through one example that shows how I could contribute."}
  ]},
  {id:"s6",question:"The interviewer asks whether you have questions.",choices:["Say no because asking questions could seem demanding.","Ask only how quickly you can be promoted.","Ask what success in the role would look like after the first several months.","Ask a question that was already answered clearly."],correct:2,feedback:[
    {heading:"Having no questions can look like low preparation or low interest.",impact:"The interviewer loses an opportunity to see your curiosity, judgment, and concern for doing the job well.",coaching:"Prepare at least three questions and choose one or two that were not already answered.",sample:"Yes, thank you. What would you want the person in this role to accomplish during the first 90 days?"},
    {heading:"Promotion-only questions make the conversation self-focused.",impact:"Ambition is not wrong, but asking only about advancement may suggest that the current role is merely a temporary stop.",coaching:"First ask about performance, priorities, training, or team needs. Ask about growth after showing commitment to succeeding in the role.",sample:"What does strong performance look like in this position, and what development opportunities become available after someone demonstrates that performance?"},
    {heading:"Strong choice: this question focuses on contribution.",impact:"It demonstrates preparation, future thinking, and interest in meeting the employer’s real expectations.",coaching:"Make it even stronger by using the employer’s timeline or priorities mentioned earlier in the interview.",sample:"Six months from now, what results would make you feel that hiring me was the right decision?"},
    {heading:"Repeating an answered question suggests weak listening.",impact:"Even a good prepared question loses value if the interviewer already addressed it clearly.",coaching:"Acknowledge what you heard and ask a thoughtful follow-up instead of repeating the original question.",sample:"You mentioned that the first month focuses on training. What tends to separate people who become productive quickly from those who struggle?"}
  ]}
];

const objectOrEmpty=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
function normalizeWorkbook(raw){
  const clean=emptyWorkbook();if(!raw||typeof raw!=="object")return clean;
  const styles=objectOrEmpty(raw.styles),mindsetValues=objectOrEmpty(raw.mindsets),body=objectOrEmpty(raw.body),scenarioValues=objectOrEmpty(raw.scenarios),choices=objectOrEmpty(raw.choices);
  styleQuestions.forEach(([id])=>{const value=Number(styles[id]);if([1,2,3,4].includes(value))clean.styles[id]=value});
  mindsets.forEach(({id})=>{const value=Number(mindsetValues[id]);if([1,2,3,4].includes(value))clean.mindsets[id]=value});
  mechanics.forEach(({id})=>{if(["Needs practice","Developing","Usually confident"].includes(body[id]))clean.body[id]=body[id]});
  scenarios.forEach(({id})=>{const value=Number(scenarioValues[id]);if([0,1,2,3].includes(value))clean.scenarios[id]=value});
  if(typeof choices.presenceChoice==="string")clean.choices.presenceChoice=choices.presenceChoice;
  if(pages.includes(raw.lastPage))clean.lastPage=raw.lastPage;
  if(typeof raw.updatedAt==="string")clean.updatedAt=raw.updatedAt;
  return clean;
}
function answerCount(){return Object.keys(workbook.mindsets).length+Object.keys(workbook.body).length+Object.keys(workbook.styles).length+Object.keys(workbook.scenarios).length+Object.keys(workbook.choices).length}
function setSaveNotice(message,type=""){const notice=document.getElementById("saveNotice");if(!notice)return;notice.textContent=message;notice.classList.toggle("save-error",type==="error");notice.classList.toggle("save-restored",type==="restored")}
function loadSaved(){try{const raw=localStorage.getItem(storageKey);if(!raw)return;workbook=normalizeWorkbook(JSON.parse(raw));restoredSession=answerCount()>0}catch{storageWorks=false}}
function save({quiet=false}={}){workbook.version=2;workbook.updatedAt=new Date().toISOString();try{localStorage.setItem(storageKey,JSON.stringify(workbook));storageWorks=true;if(!quiet)setSaveNotice(`✓ Saved ${answerCount()} responses on this device at ${new Date(workbook.updatedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}.`)}catch{storageWorks=false;setSaveNotice("Your browser is blocking local saving. Use Download Backup before leaving this course.","error")}}

function render(){
  document.getElementById("mindsetCards").innerHTML=mindsets.map((m,i)=>`<article><h2>${i+1}. ${m.title}</h2><p>${m.meaning}</p><strong>INTERVIEW VALUE</strong><p>${m.use}</p></article>`).join("");
  document.getElementById("mindsetQuestions").innerHTML=mindsets.map((m,i)=>ratingRow(`mindset-${m.id}`,`How useful would “${m.title}” be for you?`,i,workbook.mindsets[m.id])).join("");
  document.getElementById("mechanicCards").innerHTML=mechanics.map(m=>`<article><b>${m.icon}</b><h2>${m.title}</h2><p>${m.text}</p></article>`).join("");
  document.getElementById("bodyQuestions").innerHTML=mechanics.map(m=>`<div class="body-question"><p><strong>${m.title}</strong></p>${["Needs practice","Developing","Usually confident"].map(v=>`<label><input type="radio" name="body-${m.id}" value="${v}" ${workbook.body[m.id]===v?"checked":""}><span>${v}</span></label>`).join("")}</div>`).join("");
  document.getElementById("styleQuestions").innerHTML=styleQuestions.map((q,i)=>ratingRow(`style-${q[0]}`,q[2],i,workbook.styles[q[0]])).join("");
  document.getElementById("scenarioQuestions").innerHTML=scenarios.map((s,i)=>{
    const selected=workbook.scenarios[s.id],answered=Number.isInteger(selected),feedback=answered?s.feedback[selected]:null,isCorrect=answered&&selected===s.correct;
    return `<article class="scenario"><h2>${i+1}. ${s.question}</h2><p>Choose the strongest response. Every choice gives different coaching.</p><div class="scenario-options">${s.choices.map((c,j)=>`<label class="${selected===j?"selected":""}"><input type="radio" name="scenario-${s.id}" value="${j}" ${selected===j?"checked":""}><span>${String.fromCharCode(65+j)}</span><b>${c}</b></label>`).join("")}</div>${answered?`<div class="scenario-feedback ${isCorrect?"correct":"review"}"><div class="feedback-heading"><span>${isCorrect?"✓":"↻"}</span><strong>${feedback.heading}</strong></div><p><b>What this may communicate:</b> ${feedback.impact}</p><p><b>${isCorrect?"Make it stronger":"How to improve it"}:</b> ${feedback.coaching}</p><div class="sample-answer"><b>Practice saying:</b><q>${feedback.sample}</q></div></div>`:`<div class="scenario-feedback empty">Select an answer to receive specific feedback and a stronger sample response.</div>`}</article>`;
  }).join("");
  restoreSimpleChoices();bindInputs();updateStyleResult();updateSummary();
}
function ratingRow(name,text,index,value){return `<div class="rating-row"><p><span>${index+1}</span>${text}</p><div class="rating-options">${[1,2,3,4].map(n=>`<label><input type="radio" name="${name}" value="${n}" ${value===n?"checked":""}><span>${n}</span></label>`).join("")}</div></div>`}
function bindInputs(){
  document.querySelectorAll('input[name^="mindset-"]').forEach(el=>el.onchange=()=>{workbook.mindsets[el.name.replace("mindset-","")]=Number(el.value);save();updateSummary()});
  document.querySelectorAll('input[name^="body-"]').forEach(el=>el.onchange=()=>{workbook.body[el.name.replace("body-","")]=el.value;save();updateSummary()});
  document.querySelectorAll('input[name^="style-"]').forEach(el=>el.onchange=()=>{workbook.styles[el.name.replace("style-","")]=Number(el.value);save();updateStyleResult();updateSummary()});
  document.querySelectorAll('input[name^="scenario-"]').forEach(el=>el.onchange=()=>{workbook.scenarios[el.name.replace("scenario-","")]=Number(el.value);save();render()});
  document.querySelectorAll('.choice input').forEach(el=>el.onchange=()=>{workbook.choices[el.name]=el.value;save();restoreSimpleChoices();updateSummary()});
}
function restoreSimpleChoices(){document.querySelectorAll('.choice input').forEach(el=>{el.checked=workbook.choices[el.name]===el.value;el.closest("label").classList.toggle("selected",el.checked)})}
function styleScores(){return Object.keys(styleInfo).map(key=>{const related=styleQuestions.filter(q=>q[1]===key),total=related.reduce((sum,q)=>sum+(workbook.styles[q[0]]||0),0);return{key,total,average:total/related.length}}).sort((a,b)=>b.total-a.total||a.key.localeCompare(b.key))}

function evenProfile(score,overall,scores){
  const profiles={
    1:{title:"Interview skills are at a starting point",description:"None of these behaviors feels consistent yet. That is useful information—not a failure. Build a basic routine before trying to identify a signature style.",strengths:["A clear starting point","An honest self-assessment","Every skill can be practiced"],watch:"Do not try to improve all 15 behaviors at once.",action:"Prepare one honest work example, record a 60-second introduction, and practice ending with a two-second pause.",kind:"starting"},
    2:{title:"Developing interview range",description:"You sometimes use all five strength styles, but none is dependable yet. Repetition—not a personality change—is the next step.",strengths:["Some access to every style","Balanced self-view","Room to choose a style intentionally"],watch:"Inconsistent skills may disappear when pressure rises.",action:"Record one answer twice: first naturally, then with a clear ending, one specific example, and a thoughtful pause.",kind:"developing"},
    3:{title:"Balanced and dependable interview style",description:"You use all five styles often. Your advantage is range: confidence, honesty, warmth, attention, and energy.",strengths:["Consistent range","Ability to adjust to the room","No obvious style gap"],watch:"Balanced answers can still sound generic without specific evidence.",action:"Prepare three examples: a result, a challenge, and a lesson learned.",kind:"balanced"},
    4:{title:"Versatile interview communicator",description:"You report using every interview strength consistently. The goal is refinement: match the room and support confidence with evidence.",strengths:["Strong range across all five styles","High reported confidence","Ability to create energy and trust"],watch:"A perfect self-rating can hide blind spots. Confirm it through a recorded mock interview or outside feedback.",action:"Record a mock interview and ask someone what felt strongest and what felt overused.",kind:"versatile"}
  };
  return{...profiles[score],scores,overall,priorityItems:[]};
}
function styleProfile(){
  if(Object.keys(workbook.styles).length!==styleQuestions.length)return null;
  const scores=styleScores(),overall=styleQuestions.reduce((sum,[id])=>sum+workbook.styles[id],0)/styleQuestions.length,spread=scores[0].total-scores.at(-1).total,values=new Set(styleQuestions.map(([id])=>workbook.styles[id]));
  const lowest=styleQuestions.map(([id,key,text])=>({id,key,text,value:workbook.styles[id]})).sort((a,b)=>a.value-b.value);
  if(values.size===1)return evenProfile(overall,overall,scores);
  if(spread<=1){const title=overall>=3.5?"Versatile interview communicator":overall>=2.75?"Balanced and dependable interview style":"Developing interview range";return{title,description:`Your five scores are nearly even. The result should not force a false label. Your overall average is ${overall.toFixed(1)} out of 4.`,strengths:["Range across several approaches","Potential to adapt to different interviewers","No single style dominates"],watch:"Build proof for your self-ratings through practice and outside feedback.",action:overall>=3?"Use a mock interview to confirm which style appears strongest to another person.":"Choose one low-rated behavior and repeat it in three recorded answers.",scores,overall,priorityItems:lowest.slice(0,3),kind:"balanced"}}
  const top=scores[0],second=scores[1],tied=scores.filter(s=>s.total===top.total),topInfo=styleInfo[top.key],secondInfo=styleInfo[second.key];
  return{title:tied.length>1?`Blended strengths: ${tied.slice(0,2).map(s=>styleInfo[s.key].name).join(" + ")}`:`${topInfo.name} with ${secondInfo.name} support`,description:tied.length>1?`Two styles share the lead. You are strongest when you combine ${tied.slice(0,2).map(s=>styleInfo[s.key].name.toLowerCase()).join(" and ")}.`:`${topInfo.description} Your secondary ${secondInfo.name.toLowerCase()} strength gives you another way to connect.`,strengths:[...topInfo.strengths,`Secondary strength: ${secondInfo.name}`],watch:topInfo.watch,action:topInfo.practice,scores,overall,priorityItems:lowest.slice(0,3),kind:"distinct"};
}
function scoreBars(scores){return `<div class="style-score-bars">${scores.map(s=>`<div><span>${styleInfo[s.key].name}</span><div><i style="width:${s.total/12*100}%"></i></div><strong>${s.total}/12</strong></div>`).join("")}</div>`}
function coachingList(profile){return profile.priorityItems.length?`<div class="coaching-panel"><h3>Your lowest-rated behaviors become the practice plan</h3><ol>${profile.priorityItems.map(item=>`<li><strong>${styleInfo[item.key].name} — rated ${item.value}:</strong> ${questionCoaching[item.id]}</li>`).join("")}</ol></div>`:`<p class="result-action"><strong>Best next move:</strong> ${profile.action}</p>`}
function updateStyleResult(){const box=document.getElementById("liveStyleResult"),count=Object.keys(workbook.styles).length;if(count<styleQuestions.length){box.innerHTML=`<strong>${count} of ${styleQuestions.length} completed.</strong><p>Finish every statement to receive a strength pattern, score comparison, watch-out, and specific practice plan.</p>`;return}const profile=styleProfile();box.innerHTML=`<p class="kicker">YOUR RESULT</p><h2>${profile.title}</h2><p>${profile.description}</p>${scoreBars(profile.scores)}<p><strong>Watch-out:</strong> ${profile.watch}</p>${coachingList(profile)}`}

function mindsetProfile(){
  if(Object.keys(workbook.mindsets).length<6)return null;
  const ranked=mindsets.map(m=>({...m,value:workbook.mindsets[m.id]})).sort((a,b)=>b.value-a.value),values=new Set(ranked.map(x=>x.value));
  if(values.size===1){const rating=ranked[0].value;if(rating===4)return{title:"All six mindsets feel essential",description:"There is no honest single winner. Turn them into a short routine.",action:"Use three cues: I will be okay; I will be honest; I will explore mutual fit."};if(rating===1)return{title:"No mindset stands out yet",description:"These ideas do not feel useful right now. Test one simple idea instead of forcing belief.",action:"Say: “This is a professional conversation, not a life-or-death test.”"};return{title:"The six mindsets are equally useful",description:`You rated every mindset ${rating} out of 4, so the result will not arbitrarily choose one.`,action:"Choose the one that addresses your biggest interview pressure and write it at the top of your notes."}}
  const leaders=ranked.filter(x=>x.value===ranked[0].value);if(leaders.length>1)return{title:`Top priorities: ${leaders.slice(0,2).map(x=>x.title).join(" + ")}`,description:"More than one mindset tied for your highest usefulness rating.",action:`Use “${leaders[0].title}” before the interview and “${leaders[1].title}” while answering.`};
  return{title:ranked[0].title,description:ranked[0].use,action:`Write this cue on your notes: “${ranked[0].title}.”`};
}
function scenarioProfile(){const completed=Object.keys(workbook.scenarios).length,correct=scenarios.filter(s=>workbook.scenarios[s.id]===s.correct).length;if(!completed)return{correct,completed,label:"Not started",direction:"Complete the six scenarios and review why each strongest response works."};if(completed<6)return{correct,completed,label:"In progress",direction:`Complete the remaining ${6-completed} scenarios and review every explanation.`};if(correct===6)return{correct,completed,label:"Strong interview judgment",direction:"Now say the strongest choices aloud in your own words."};if(correct>=4)return{correct,completed,label:"Solid judgment with a few gaps",direction:"Revisit the missed scenarios and explain why the recommended response is stronger."};return{correct,completed,label:"Needs targeted review",direction:"Repeat the lab and focus on honesty, relevance, pauses, and mutual fit."}}
function updateSummary(){
  const styleCount=Object.keys(workbook.styles).length,mindsetCount=Object.keys(workbook.mindsets).length,bodyCount=Object.keys(workbook.body).length,profile=styleProfile(),mindset=mindsetProfile(),scenario=scenarioProfile();
  const bodyNeeds=mechanics.filter(m=>workbook.body[m.id]==="Needs practice"),practiceTargets=(bodyNeeds.length?bodyNeeds:mechanics.filter(m=>workbook.body[m.id]==="Developing")).slice(0,3);
  const actions=[mindset?mindset.action:"Complete the mindset ratings and choose one mental cue.",practiceTargets[0]?`Record one answer while practicing “${practiceTargets[0].title}.”`:"Choose one body-language skill to practice on video.",profile?profile.action:"Complete the strength-style statements for a targeted practice step."];
  document.getElementById("summaryContent").innerHTML=`
    <div class="summary-progress"><strong>${answerCount()} saved responses</strong><span>Mindsets ${mindsetCount}/6 • Body language ${bodyCount}/6 • Strength style ${styleCount}/15 • Practice ${scenario.completed}/6</span></div>
    <div class="summary-grid"><article class="summary-card highlight"><p class="kicker">MY INTERVIEW PATTERN</p><h2>${profile?profile.title:"Assessment not complete"}</h2><p>${profile?profile.description:`Complete all 15 statements (${styleCount}/15 completed).`}</p></article><article class="summary-card alert"><p class="kicker">MY MINDSET DIRECTION</p><h2>${mindset?mindset.title:"Assessment not complete"}</h2><p>${mindset?mindset.description:`Complete all six ratings (${mindsetCount}/6 completed).`}</p></article></div>
    <article class="summary-card"><h2>Strengths and Growth Direction</h2>${profile?`<ul>${profile.strengths.map(x=>`<li>${x}</li>`).join("")}</ul><p><strong>Watch-out:</strong> ${profile.watch}</p>${scoreBars(profile.scores)}${coachingList(profile)}`:"<p>Complete Module 4 to compare all five styles and build a plan from your lowest-rated behaviors.</p>"}</article>
    <article class="summary-card"><h2>Body-Language Practice</h2><p>${bodyCount}/6 skills reviewed.</p>${practiceTargets.length?`<ul>${practiceTargets.map(x=>`<li><strong>${x.title}:</strong> ${x.text}</li>`).join("")}</ul>`:"<p>Complete Module 3 or continue practicing all six skills.</p>"}</article>
    <article class="summary-card good"><h2>Practice-Lab Result: ${scenario.label}</h2><p><strong>${scenario.correct} of ${scenario.completed} completed scenarios used the strongest response.</strong></p><p>${scenario.direction}</p></article>
    <article class="summary-card"><h2>My Three Next Steps</h2><ol>${actions.map(x=>`<li>${x}</li>`).join("")}</ol></article>
    <div class="notice"><strong>Final reminder:</strong> Presence supports substance; it does not replace preparation. Use honest examples, connect experience to employer needs, and ask thoughtful questions.</div>`;
}

function showPage(id,{updateHistory=true,remember=true}={}){if(!pages.includes(id))id="home";document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.dataset.pagePanel===id));document.querySelectorAll(".course-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));const i=pages.indexOf(id),previous=document.getElementById("previousPage"),next=document.getElementById("nextPage"),final=i===pages.length-1;document.getElementById("pageCount").textContent=`${i+1} of ${pages.length}`;previous.disabled=i===0;previous.dataset.target=pages[Math.max(0,i-1)];next.disabled=false;next.dataset.target=final?"academy-home":pages[i+1];next.textContent=final?"Course Complete →":"Next →";next.setAttribute("aria-label",final?"Course complete, return to Academy Home":"Go to the next course page");if(updateHistory)history.replaceState(null,"",`#${id}`);if(remember&&workbook.lastPage!==id){workbook.lastPage=id;save({quiet:true})}window.scrollTo({top:0,behavior:"smooth"})}
function download(name,text,type="application/json"){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

loadSaved();render();
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showPage(b.dataset.go));document.getElementById("previousPage").onclick=e=>showPage(e.currentTarget.dataset.target);document.getElementById("nextPage").onclick=e=>{const target=e.currentTarget.dataset.target;if(target==="academy-home")window.location.href="../index.html";else showPage(target)};
document.getElementById("downloadWorkbook").onclick=()=>download("HFTB_Interview_Skills_Workbook.json",JSON.stringify(workbook,null,2));document.getElementById("loadWorkbook").onclick=()=>document.getElementById("workbookFile").click();document.getElementById("workbookFile").onchange=async e=>{try{workbook=normalizeWorkbook(JSON.parse(await e.target.files[0].text()));save();render();showPage("summary")}catch{alert("That file is not a valid Interview Skills workbook.")}e.target.value=""};
document.getElementById("startFresh").onclick=()=>{if(confirm("Clear all Interview Skills answers stored in this browser?")){workbook=emptyWorkbook();try{localStorage.removeItem(storageKey)}catch{}render();setSaveNotice("Answers cleared. New answers will save automatically in this browser.");showPage("home",{remember:false})}};
document.getElementById("printSummary").onclick=()=>window.print();document.getElementById("downloadSummary").onclick=()=>download("HFTB_My_Interview_Readiness_Summary.txt",`HOMES FOR THE BRAVE\nINTERVIEW PRESENCE & CONFIDENCE\n\n${document.getElementById("summaryContent").innerText}`,"text/plain");
const requested=location.hash.slice(1),initial=pages.includes(requested)?requested:(restoredSession&&pages.includes(workbook.lastPage)?workbook.lastPage:"home");showPage(initial,{updateHistory:Boolean(requested),remember:false});
if(!storageWorks)setSaveNotice("Your browser is blocking local saving. Use Download Backup before leaving this course.","error");else if(restoredSession)setSaveNotice(`Welcome back — restored ${answerCount()} saved responses from ${workbook.updatedAt?new Date(workbook.updatedAt).toLocaleString():"an earlier visit"}. You are continuing where you stopped.`,"restored");
